from ..attributes import ID_MODEL_ID, ID_VENDOR, ID_MODEL, ID_VENDOR_FROM_DATABASE, ID_MODEL_FROM_DATABASE, \
    DEVNAME, ID_USB_CLASS_FROM_DATABASE, ID_USB_INTERFACES, DEVTYPE

_DEVICE_ID, _PNP_DEVICE_ID = 'DeviceID', 'PNPDeviceID'

_LINUX_TO_WINDOWS_ATTRIBUTES = {
    ID_MODEL_ID: 'HardwareID',
    ID_VENDOR: 'HardwareID',
    ID_MODEL: 'Name',
    ID_VENDOR_FROM_DATABASE: 'Manufacturer',#'Description',
    ID_MODEL_FROM_DATABASE: 'Caption',
    DEVNAME: _DEVICE_ID,
    ID_USB_CLASS_FROM_DATABASE: 'PNPClass',
    ID_USB_INTERFACES: 'CompatibleID',
    DEVTYPE: _PNP_DEVICE_ID,
}

_SECONDS_BETWEEN_CHECKS = 1